# Generated by Django 3.2.15 on 2022-08-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11)),
                ('phone_code', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=10)),
                ('time_zone', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('datetime_start', models.DateTimeField()),
                ('message', models.CharField(max_length=1000)),
                ('datetime_end', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Mailing',
                'verbose_name_plural': 'Mailings',
                'ordering': ['-id'],
            },
        ),
    ]
