# Generated by Django 3.2.15 on 2022-08-05 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('is_sent', models.BooleanField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_client', to='api.client')),
                ('mailing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_mailing', to='api.mailing')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-id'],
            },
        ),
    ]
