# Generated by Django 3.2.15 on 2022-08-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220809_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
